### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by optilude** [ActionableAgile/jira-to-analytics#1]
Errors are often swallowed silently. For example, if the values in the `Connection` section are wrong, an empty CSV file will be written without any sign that the program failed to connect to JIRA.

Similarly, if statuses in the workflow don't actually exist, this appears to be ignored.

**Comment by ActionableAgile** [comment]
Connection errors are now handled properly, and I've added the -u option that displays unused Jira workflow stages.
