### ISSUE TITLE
Make JIRA statuses case-insensitive

### ISSUE THREAD

**Issue by optilude** [ActionableAgile/jira-to-analytics#3]
JIRA always prints workflow statuses in all upper-case. This means that it is actually quite hard to work out what the actual case-sensitive name of a workflow status is[1]. It would be good if jira-to-analytics didn't care, as unknown statuses are silently ignored.

[1] One way is to hit the API endpoint in your browser, e.g. `https://<server>/rest/api/2/project/<projectKey>/statuses`

**Comment by ActionableAgile** [comment]
The latest version of the tool ignores the case of the Jira workflow stages (statuses).
