### ISSUE TITLE
Labels attribute is not very useful

### ISSUE THREAD

**Issue by optilude** [ActionableAgile/jira-to-analytics#4]
When extracting labels (one of the examples in the default `config.yaml`) you get a flattened, semicolon-separated list for any issues with more than one label. This is pretty useless. It would be better if the Analytics tool could understand this and present all individual labels as filter options.

**Comment by ActionableAgile** [comment]
Analytics will probably support this in the future, but regardless this is the best behavior for jira-to-analytics. There's nothing to be done in this project.
