### ISSUE TITLE
JIRA and OAUTH

### ISSUE THREAD

**Issue by rj175** [ActionableAgile/jira-to-analytics#41]
Hello,

Not sure if this is the right place to ask this but has anyone managed to get JIRA and Oauth working? I have generated the public/private RSA keys, added them in and also ran a script to get the oauth tokens. I can see that the applications is using my oauth keys but when I try and run the jira-to-analytics.exe I get an authentication error.

Am I missing something?

Richard

**Comment by toddconley** [comment]
Hi Richard,

I asked around and heard of one case where someone got OAuth working with
an on-prem Jira instance, so it's likely that everything you need is there.
If you succeed, be sure to add some helpful documentation to the project!

Sorry I can't be any more helpful.

Todd Conley
