### ISSUE TITLE
First attribute is spuriously used as workflow stage

### ISSUE THREAD

**Issue by optilude** [ActionableAgile/jira-to-analytics#6]
Kind of a weird one. I have this config:

```
Connection:
  Domain: XXXX
  Username: XXXX

Criteria:
  Projects: XX
  Filters: 12345
  Types: Bug, Story

Workflow:
  Open: Open
  Analysis IP: Analysis in Progress
  Analysis Done: Analysis Done
  Sign-off IP: Sign off in Progress
  Sign-off Done: Sign off done
  Development IP: Development in progress
  Development Done: Development Done
  Tech QA IP: Tech QA in progress
  Tech QA Done: Tech QA Done
  BA QA IP: BA qa in progress
  BA QA Done: ba qa done
  Test: Test qa in progress
  Test Done: test qa done
  Done: Closed, Done

Attributes:
  Team: components
  Stage: status
  Type: issuetype
  Priority: priority
```

When I export this, I get a spurious last workflow state called `Team` after `Done` and no `Team` attribute in the filter.

**Comment by optilude** [comment]
Interestingly, this stops happening if I switch `Team` and `Stage` in the list above so `Stage` comes first.

**Comment by ActionableAgile** [comment]
ActionableAgile Analytics infers the meaning of the columns by looking at their content. When a column is empty (meaning none of the rows have data in that column), the tool tries to infer whether the column is a workflow stage or an attribute, but it can't tell the difference between and empty last workflow stage and an empty first attribute. In this case we have chosen to interpret the column as a workflow stage. I suspect that is what is happening here.
