### ISSUE TITLE
Not possible to filter by fixVersion or components

### ISSUE THREAD

**Issue by optilude** [ActionableAgile/jira-to-analytics#7]
JIRA uses `fixVersion` to signify releases, so it's a useful attribute to filter by.

However, if I add this to the `Attributes` section, I get an error `Unknown attribute fixVersion`

It is also not possible to filter by `components`. No error on this one, but it just produces a blank column.

**Comment by ActionableAgile** [comment]
Those attributes weren't implemented properly. They're fixed now.

Note that the attribute name is fixVersions, not fixVersion.
