### ISSUE TITLE
Cumulative Flow Diagram has broken statistics when changing dates 

### ISSUE THREAD

**Issue by cmshar** [ActionableAgile/jira-to-analytics#73]
When I change the dates in the lower panel in the Cumulative Flow Diagram, the statistics break. 

<img width="1081" alt="Screen Shot 2020-08-20 at 1 06 57 PM" src="https://user-images.githubusercontent.com/47576319/90808764-250a2a00-e2e6-11ea-8dcb-d7d65a78e98f.png">

**Comment by seanmillerio** [comment]
I experienced this as well, this isn’t related to the jira-to-analytics app though, you need to contact ActionableAgile Support. They don’t maintain this any longer.

**Comment by cmshar** [comment]
Thanks! I'll log a ticket there and close this then.
