### ISSUE TITLE
Username and Password should be optional

### ISSUE THREAD

**Issue by mshahzadz** [ActionableAgile/jira-to-analytics#9]
Our JIRA instance is currently setup within the firewall. Generally, if I am making a Rest call, I can call the API without logging in and get read-only access, as long as within the firewall. We are deploying this utility centrally to run on a nightly basis, so had to create a generic read-only JIRA account, so the utility can work easily for everyone and for individuals not have to add their password in the file.

Ideally, would want these fields to be optional.

**Comment by johnrjj** [comment]
Now supported in the TypeScript version!
